### ISSUE TITLE
Finish DOS function in utils.go

### ISSUE THREAD

**Issue by ScreamingTaco** [TheRedSpy15/Multi-Go#26]
As mentioned previously, I'm opening issues for any TODOs I find in the code that need it. There is a comment above the `Dos` function in `utils.go` that says the function is incomplete. I don't know what is not complete about it (maybe @TheRedSpy15 can shed some light on it), but now the issue is public at least.

**Comment by gavinwade12** [comment]
I see why you are having problems with it. I'll fix it.

**Comment by TheRedSpy15** [comment]
fixed with #34 thanks to @gavinwade12
